apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: kamran623/ultimate-cicd:62
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  # optional, use what your app needs

